#
# PySNMP MIB module NET-SNMP-EXAMPLES-MIB (http://pysnmp.sf.net)
# ASN.1 source http://mibs.snmplabs.com:80/asn1/NET-SNMP-EXAMPLES-MIB
# Produced by pysmi-0.0.6 at Sun Dec  6 17:40:54 2015
# On host ? platform ? version ? by user ?
# Using Python version 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
#
( OctetString, ObjectIdentifier, Integer, ) = mibBuilder.importSymbols("ASN1", "OctetString", "ObjectIdentifier", "Integer")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ValueRangeConstraint, ValueSizeConstraint, ConstraintsUnion, ConstraintsIntersection, SingleValueConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ValueRangeConstraint", "ValueSizeConstraint", "ConstraintsUnion", "ConstraintsIntersection", "SingleValueConstraint")
( InetAddress, InetAddressType, ) = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddress", "InetAddressType")
( netSnmp, ) = mibBuilder.importSymbols("NET-SNMP-MIB", "netSnmp")
( SnmpAdminString, ) = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
( NotificationGroup, ModuleCompliance, ) = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance")
( Unsigned32, MibScalar, MibTable, MibTableRow, MibTableColumn, IpAddress, ObjectIdentity, ModuleIdentity, iso, Gauge32, NotificationType, TimeTicks, MibIdentifier, Counter32, Integer32, Counter64, Bits, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Unsigned32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "IpAddress", "ObjectIdentity", "ModuleIdentity", "iso", "Gauge32", "NotificationType", "TimeTicks", "MibIdentifier", "Counter32", "Integer32", "Counter64", "Bits")
( RowStatus, StorageType, DisplayString, TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "RowStatus", "StorageType", "DisplayString", "TextualConvention")
netSnmpExamples = ModuleIdentity((1, 3, 6, 1, 4, 1, 8072, 2)).setRevisions(("2004-06-15 00:00", "2002-02-06 00:00",))
netSnmpExampleScalars = MibIdentifier((1, 3, 6, 1, 4, 1, 8072, 2, 1))
netSnmpExampleTables = MibIdentifier((1, 3, 6, 1, 4, 1, 8072, 2, 2))
netSnmpExampleNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 8072, 2, 3))
netSnmpExampleNotificationPrefix = MibIdentifier((1, 3, 6, 1, 4, 1, 8072, 2, 3, 0))
netSnmpExampleNotificationObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 8072, 2, 3, 2))
netSnmpExampleInteger = MibScalar((1, 3, 6, 1, 4, 1, 8072, 2, 1, 1), Integer32().clone(42)).setMaxAccess("readwrite")
netSnmpExampleSleeper = MibScalar((1, 3, 6, 1, 4, 1, 8072, 2, 1, 2), Integer32().clone(1)).setMaxAccess("readwrite")
netSnmpExampleString = MibScalar((1, 3, 6, 1, 4, 1, 8072, 2, 1, 3), SnmpAdminString().clone('So long, and thanks for all the fish!')).setMaxAccess("readwrite")
netSnmpIETFWGTable = MibTable((1, 3, 6, 1, 4, 1, 8072, 2, 2, 1), )
netSnmpIETFWGEntry = MibTableRow((1, 3, 6, 1, 4, 1, 8072, 2, 2, 1, 1), ).setIndexNames((0, "NET-SNMP-EXAMPLES-MIB", "nsIETFWGName"))
nsIETFWGName = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 1, 1, 1), OctetString().subtype(subtypeSpec=ValueSizeConstraint(1,32)))
nsIETFWGChair1 = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 1, 1, 2), OctetString()).setMaxAccess("readcreate")
nsIETFWGChair2 = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 1, 1, 3), OctetString()).setMaxAccess("readcreate")
netSnmpHostsTable = MibTable((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2), )
netSnmpHostsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2, 1), ).setIndexNames((0, "NET-SNMP-EXAMPLES-MIB", "netSnmpHostName"))
netSnmpHostName = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2, 1, 1), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0,64)))
netSnmpHostAddressType = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2, 1, 2), InetAddressType()).setMaxAccess("readcreate")
netSnmpHostAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2, 1, 3), InetAddress()).setMaxAccess("readcreate")
netSnmpHostStorage = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2, 1, 4), StorageType().clone('nonVolatile')).setMaxAccess("readcreate")
netSnmpHostRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 8072, 2, 2, 2, 1, 5), RowStatus()).setMaxAccess("readcreate")
netSnmpExampleHeartbeatRate = MibScalar((1, 3, 6, 1, 4, 1, 8072, 2, 3, 2, 1), Integer32()).setMaxAccess("accessiblefornotify")
netSnmpExampleHeartbeatName = MibScalar((1, 3, 6, 1, 4, 1, 8072, 2, 3, 2, 2), SnmpAdminString()).setMaxAccess("accessiblefornotify")
netSnmpExampleHeartbeatNotification = NotificationType((1, 3, 6, 1, 4, 1, 8072, 2, 3, 0, 1)).setObjects(*(("NET-SNMP-EXAMPLES-MIB", "netSnmpExampleHeartbeatRate"),))
netSnmpExampleNotification = MibScalar((1, 3, 6, 1, 4, 1, 8072, 2, 3, 1), SnmpAdminString()).setMaxAccess("accessiblefornotify")
mibBuilder.exportSymbols("NET-SNMP-EXAMPLES-MIB", netSnmpHostAddress=netSnmpHostAddress, netSnmpExampleTables=netSnmpExampleTables, netSnmpExampleInteger=netSnmpExampleInteger, netSnmpHostsTable=netSnmpHostsTable, nsIETFWGChair1=nsIETFWGChair1, netSnmpHostRowStatus=netSnmpHostRowStatus, netSnmpExampleHeartbeatName=netSnmpExampleHeartbeatName, netSnmpExamples=netSnmpExamples, nsIETFWGName=nsIETFWGName, netSnmpExampleSleeper=netSnmpExampleSleeper, netSnmpHostName=netSnmpHostName, netSnmpExampleNotification=netSnmpExampleNotification, netSnmpHostStorage=netSnmpHostStorage, PYSNMP_MODULE_ID=netSnmpExamples, netSnmpExampleScalars=netSnmpExampleScalars, netSnmpIETFWGTable=netSnmpIETFWGTable, netSnmpExampleHeartbeatRate=netSnmpExampleHeartbeatRate, netSnmpExampleHeartbeatNotification=netSnmpExampleHeartbeatNotification, netSnmpExampleNotifications=netSnmpExampleNotifications, netSnmpExampleString=netSnmpExampleString, netSnmpHostsEntry=netSnmpHostsEntry, nsIETFWGChair2=nsIETFWGChair2, netSnmpExampleNotificationObjects=netSnmpExampleNotificationObjects, netSnmpExampleNotificationPrefix=netSnmpExampleNotificationPrefix, netSnmpHostAddressType=netSnmpHostAddressType, netSnmpIETFWGEntry=netSnmpIETFWGEntry)
